version: "3"

services:
    php_cli:
        image: thecodingmachine/php:8.1.0-v4-cli
        container_name: webapp_php_cli
        ports:
            - "9000:9000"
            - "9003:9003"
        volumes:
            - .:/application
        working_dir: "/application"
        environment:
            PHP_EXTENSION_XDEBUG: 1
            XDEBUG_CONFIG: remote_host=host.docker.internal
            STARTUP_COMMAND_1: composer install
        networks:
            traefik:
                ipv4_address: 172.16.20.1

    php_apache:
        image: thecodingmachine/php:8.1-v4-apache
        container_name: webapp_php_apache
        ports:
            - "80:80"
            - "443:443"
            - "9000:9000"
            - "9003:9003"
        volumes:
            - .:/var/www/html
        working_dir: "/var/www/html"
        environment:
            PHP_EXTENSION_XDEBUG: 1
            XDEBUG_CONFIG: remote_host=host.docker.internal
            STARTUP_COMMAND_1: composer install
        networks:
            traefik:
                ipv4_address: 172.16.20.2

    database:
        image: mysql:8.0
        container_name: webapp_db
        ports:
            - "5432:5432"
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=webapp
            - MYSQL_USER=webapp
            - MYSQL_PASSWORD=webapp
        networks:
            traefik:
                ipv4_address: 172.16.20.33

networks:
    traefik:
        external: true